const mockedCompanyData = [
  {
    ticker: "IBM",
    logo: "https://cdn.iconscout.com/icon/free/png-256/bee-189-439428.png",
    name: "International Business Machines Corp",
    country: "US",
    currency: "USD",
    weburl: "https://www.ibm.com/",
  },
  {
    ticker: "AAPL",
    logo: "https://static.finnhub.io/logo/87cb30d8-80df-11ea-8951-00000000092a.png",
    name: "Apple Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.apple.com/",
  },
  {
    ticker: "ORCL",
    logo: "https://static.finnhub.io/logo/1f119542-80e1-11ea-8adf-00000000092a.png",
    name: "Oracle Corp",
    country: "US",
    currency: "USD",
    weburl: "https://www.oracle.com/",
  },
  {
    ticker: "V",
    logo: "https://static.finnhub.io/logo/96a1dba6-80ec-11ea-8ab6-00000000092a.png",
    name: "Visa Inc",
    country: "US",
    currency: "USD",
    weburl: "https://usa.visa.com/",
  },
  {
    ticker: "GOOGL",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/GOOGL.png",
    name: "Alphabet Inc",
    country: "US",
    currency: "USD",
    weburl: "https://abc.xyz/",
  },
  {
    ticker: "MSFT",
    logo: "https://static.finnhub.io/logo/25e313016e9fac0f4b78bbd7e3afded45a8136b17f450c262aea14beed438191.png",
    name: "Microsoft Corp",
    country: "US",
    currency: "USD",
    weburl: "https://www.microsoft.com/en-us",
  },
  {
    ticker: "UNH",
    logo: "https://static.finnhub.io/logo/91f38836-80ec-11ea-a5be-00000000092a.png",
    name: "UnitedHealth Group Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.unitedhealthgroup.com/",
  },
  {
    ticker: "META",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/FB.png",
    name: "Meta Platforms Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.facebook.com",
  },
  {
    ticker: "HD",
    logo: "https://static.finnhub.io/logo/f3d21b34-80eb-11ea-9fb5-00000000092a.png",
    name: "Upstart Holdings Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.homedepot.com/",
  },
  {
    ticker: "DIS",
    logo: "https://static.finnhub.io/logo/ef50b4a2b263c847211b567a01edb702cae8b9ef46ca1f6856ca4432a70e9f52.png",
    name: "Walt Disney Co",
    country: "US",
    currency: "USD",
    weburl: "https://thewaltdisneycompany.com/",
  },
  {
    ticker: "SOFI",
    logo: "https://static.finnhub.io/logo/0a900736-80ec-11ea-8224-00000000092a.png",
    name: "Johnson & Johnson",
    country: "US",
    currency: "USD",
    weburl: "https://www.jnj.com/",
  },
];

export default mockedCompanyData;
