const mockedCompanyData = [
  {
    ticker: "AAPL",
    name: "Apple Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.apple.com/",
  },
  {
    ticker: "EOG",
    name: "EOG Resources Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.eogresources.com/",
  },
  {
    ticker: "V",
    name: "Visa Inc",
    country: "US",
    currency: "USD",
    weburl: "https://usa.visa.com/",
  },
  {
    ticker: "MED",
    name: "Medifast Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.medifast1.com",
  },
  {
    ticker: "GOOGL",
    name: "Alphabet Inc",
    country: "US",
    currency: "USD",
    weburl: "https://abc.xyz/",
  },
  {
    ticker: "MSFT",
    name: "Microsoft Corp",
    country: "US",
    currency: "USD",
    weburl: "https://www.microsoft.com/en-us",
  },
  {
    ticker: "LOW",
    name: "Lowe's Companies Inc",
    country: "US",
    currency: "USD",
    weburl: "http://media.lowes.com/",
  },
  {
    ticker: "META",
    name: "Meta Platforms Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.facebook.com",
  },
  {
    ticker: "UPST",
    name: "Upstart Holdings Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.upstart.com/",
  },
  {
    ticker: "DIS",
    name: "Walt Disney Co",
    country: "US",
    currency: "USD",
    weburl: "https://thewaltdisneycompany.com/",
  },
  {
    ticker: "SHOP",
    name: "Shopify Inc",
    country: "CA",
    currency: "USD",
    weburl: "https://www.shopify.com/",
  },
  {
    ticker: "SOFI",
    name: "SoFi Technologies Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.sofi.com/",
  },
];

export default mockedCompanyData;
