const mockedCompanyData = [
  {
    ticker: "GME",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/GME.png",
    name: "GameStop Corp",
    country: "US",
    currency: "USD",
    weburl: "https://news.gamestop.com/",
  },
  {
    ticker: "AAPL",
    logo: "https://static.finnhub.io/logo/87cb30d8-80df-11ea-8951-00000000092a.png",
    name: "Apple Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.apple.com/",
  },
  {
    ticker: "ORCL",
    logo: "https://static.finnhub.io/logo/1f119542-80e1-11ea-8adf-00000000092a.png",
    name: "Oracle Corp",
    country: "US",
    currency: "USD",
    weburl: "https://www.oracle.com/",
  },
  {
    ticker: "V",
    logo: "https://static.finnhub.io/logo/96a1dba6-80ec-11ea-8ab6-00000000092a.png",
    name: "Visa Inc",
    country: "US",
    currency: "USD",
    weburl: "https://usa.visa.com/",
  },
  {
    ticker: "GOOGL",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/GOOGL.png",
    name: "Alphabet Inc",
    country: "US",
    currency: "USD",
    weburl: "https://abc.xyz/",
  },
  {
    ticker: "MSFT",
    logo: "https://static.finnhub.io/logo/25e313016e9fac0f4b78bbd7e3afded45a8136b17f450c262aea14beed438191.png",
    name: "Microsoft Corp",
    country: "US",
    currency: "USD",
    weburl: "https://www.microsoft.com/",
  },
  {
    ticker: "CLAR",
    weburl: "https://www.claruscorp.com/",
    name: "Clarus Corp",
    country: "US",
    currency: "USD",
  },

  {
    ticker: "META",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/FB.png",
    name: "Meta Platforms Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.facebook.com",
  },
  {
    ticker: "HD",
    logo: "https://static.finnhub.io/logo/f3d21b34-80eb-11ea-9fb5-00000000092a.png",
    name: "Upstart Holdings Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.homedepot.com/",
  },
  {
    ticker: "AMD",
    logo: "https://static2.finnhub.io/file/publicdatany/finnhubimage/stock_logo/AMD_4295903297.jpeg",
    name: "Advanced Micro Devices Inc",
    country: "US",
    currency: "USD",
    weburl: "https://www.amd.com/en",
  },
  {
    ticker: "SOFI",
    logo: "https://static.finnhub.io/logo/0a900736-80ec-11ea-8224-00000000092a.png",
    name: "Johnson & Johnson",
    country: "US",
    currency: "USD",
    weburl: "https://www.jnj.com/",
  },
];

export default mockedCompanyData;
